### ISSUE TITLE
compiling u-boot for the 38x WRT models

### ISSUE THREAD

**Issue by Chadster766** [ValCher1961/McDebian_WRT3200ACM#2]
Hi Valcher1961,

Can you contact the person in you post below to find out how we can build u-boot for the WRT 38x models? This would allow us to release updates and patched version with having to rely on others for them.

https://forum.armbian.com/topic/4444-solved-kwboot-on-armada-38x/

**Comment by ValCher1961** [comment]
Hi, @Chadster766.
Yes, of course, I'll try to contact the author.
As I think, to solve this problem, we still need to know the labeling of the new NAND-chip. This will help to identify incompatibilities.

**Comment by Chadster766** [comment]
@ValCher1961 compiling u-boot for a generic Marvel 38x should be all we need. I don't really want to compile a u-boot image for upload to a WRT but instead just get the latest u-boot tools like kwboot which get compiled at the same time as u-boot image.

In the past kwboot and other u-boot tools could be compiled separately but no longer due to heavy interdependencies with the u-boot "make menuconfig" configuration.

**Comment by Chadster766** [comment]
Actually I'm having problems with kwboot in general with most WRT models.

**Comment by ValCher1961** [comment]
I looked at the source from Linksys on WRT32X_gpl.
 There are two versions of U-Boot in the source:
 U-Boot-2014.10
 U-Boot-2015.10
 But the config is not given, i.e. it is necessary to configure. There are a lot of parameters and I don't know them all.

**Comment by Chadster766** [comment]
I figured out how to compile and use the latest u-boot tools like kwboot. Below is the process I used to do the compilation.
```
git clone git.denx.de
git pull
apt-get install libssl-dev
make clean
```
Before you build the sandbox u-boot make the small modification below to the below Makefile for kwboot to be built otherwise it won't.
```
diff --git a/tools/Makefile b/tools/Makefile
index 571f571ec..bde7ab83b 100644
--- a/tools/Makefile
+++ b/tools/Makefile
@@ -182,7 +182,7 @@ ubsha1-objs := os_support.o ubsha1.o lib/sha1.o
 HOSTCFLAGS_ubsha1.o := -pedantic

 hostprogs-$(CONFIG_KIRKWOOD) += kwboot
-hostprogs-$(CONFIG_ARCH_MVEBU) += kwboot
+hostprogs-y += kwboot
 hostprogs-y += proftool
 hostprogs-$(CONFIG_STATIC_RELA) += relocate-rela
 hostprogs-$(CONFIG_RISCV) += prelink-riscv
```
Build commands:
```
make sandbox_config
make all NO_SDL=1
```
kwboot will be under the tools directory.

To load firmware run the kwboot command at the same time you power on the router. Use one of you mtd0 backup copies for kwboot load instruction as usual.
```
./kwboot -t /dev/ttyUSB0 -b ../../WRT-mtd0-backups/u-boot-wrt1200ac.bin -B 115200 -p

setenv serverip 192.168.1.2
tftp 2000000 u-boot-wrt1200ac.bin
nand erase 0 200000
nand write 2000000 0 200000
```
I discovered that some WRT u-boots are different sizes so after kwboot is finished and you do the initial tftp load of your u-boot backup binary pay attention to the output "Bytes transferred = 2097152 (200000 hex)" because this is the hex value you should used in the nand commands above. If you the wrong size for the nand commands you will get the error "BootROM: Image checksum verification FAILED" and the whole process will have to be repeated.

**Comment by Chadster766** [comment]
The kwboot patch file can be downloaded from:
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/kwboot.patch
```
