### ISSUE TITLE
reg free patch

### ISSUE THREAD

**Issue by dissent1** [ValCher1961/McDebian_WRT3200ACM#3]
@ValCher1961 Does this patch has any real effect? I do not notice any changes with or without it.
kernel-4.14.X/patch.regfree

**Comment by ValCher1961** [comment]
@dissent1 
Yes, of course, the patch allows you to change the country and open the allowed channels for the selected region. The patch is only applicable to 88w8964.
Bring your configuration.

**Comment by dissent1** [comment]
@ValCher1961 so available channels is the only effect? Because country tx power limitations are not applied neither it is possible to lower the tx power. I believe firmware still overrides this :(
WRT3200ACM v1 US version.
Is there any hack available to lower TX power? I use 5ghz only and have AP set up on per room basis, so I don't need he AP to radiate with all it's possible tx power :(

It's such a lame excuse for marvel to disable tx power management to fulfil FCC requirements... FCC doesn't forbid tx power to be lower than allowed boundaries...

**Comment by ValCher1961** [comment]
@dissent1 
I fully agree with you, this is the real dictate. We impose only one power, without the possibility of changing it within the limits of permissible values.
Unfortunately, I have not yet found a way to change the power, it remains unchanged...  (
