### ISSUE TITLE
Adding uboot directly through backup partition

### ISSUE THREAD

**Issue by avielc** [ValCher1961/McDebian_WRT3200ACM#4]
Hi @ValCher1961 
I'm kinda in a pickle and after deep digging I kinda reached your uboot bin, not sure even if its the right place, but I'm willing to do a lot now to get it working back

in short WRT32x - done a simple factory-ddwrt through GUI and it worked, Had to switch back once for work,
Tried again after and it always landed on 2 version of stock firmware. 
I tried a bunch of firmware update using stock\dd wrt eventually only backup works with no wifi and barely internet (no lights are almost on the router) 
and everytime I try to upgrade I get this message: 
cannot find ubi mtd partition rootfs2
libubi: error!: "/dev/" is not a character device
ubiupdatevol: error!: error while probing "/dev/"
              error 22 (Invalid argument)

I'm hoping the uboot might correct something partially
Could you help me out here? 
I'm trying to figure if I can install the uboot directly via ssh to the router (That I still can do to the backup, semi-dead, partition)

Thanks alot. I'm kinda desperate here

**Comment by ValCher1961** [comment]
Hi @avielc 
I think your device has been disrupted by a UBI that tracks bad NAND blocks and ensures that cell wear is aligned. If so, you need to re-format the entire NAND. This command can only be executed from Uboot. Do you have a USB TTL cable? - https://openwrt.org/toh/linksys/wrt_ac_series#serial_interfaces

**Comment by avielc** [comment]
Hi @ValCher1961 , 
Thanks for replying!
I'm afraid I don't have that cable
Can I do it without the cable? (This router is barely a week old) 
I pulled out some syslog information that someone mentioned in the dd wrt forum - 
perhaps the log at the bottom would shed some light too? 
Also, from what I saw, it looks like it doesn't see the MAC addresses of the wireless chipsets.. (kinda terrified me that I managed to brick it?)

What would you suggest I'd do next?
[
[syslog.txt](https://github.com/ValCher1961/McDebian_WRT3200ACM/files/2260104/syslog.txt)
]

**Comment by ValCher1961** [comment]
Can you show the download log  "dmesg"?

**Comment by avielc** [comment]
[dmesg.txt](https://github.com/ValCher1961/McDebian_WRT3200ACM/files/2260129/dmesg.txt)
As requested. here it is, pulled it just now

**Comment by ValCher1961** [comment]
That's where you have uncertainty 
```
[    1.174505] mtd: partition "rootfs" set to be root filesystem
[    1.180446]  magic 23494255 vs 73717368
[    1.184310] split_squashfs: no squashfs found in "pxa3xx_nand-0"
```
I think you can fix it only through Uboot.

**Comment by avielc** [comment]
Well, sounds like a minor nightmare. for me at least..
Perhaps before getting my hands dirty in it, I'd have to check out if Amazon can replace it at the very least, if they would accept it, it could save me the trouble of looking for such cable around where I live (which assuming it's not that widely available.. ) 

Can I bother you with the set of commands I'll need to fix it with Uboot, just so I can close the issue here, 
Thank you so very much for this man, 
I really appreciate the help, and sorry if i wasted your time on this.

**Comment by ValCher1961** [comment]
Oh, no worries!
Of course, if it is possible to exchange the goods, this is the best solution.
If you fail to exchange, we will try to restore the router.

**Comment by avielc** [comment]
Looks like Amazon will be able to replace the router (Phew!) 
I'll be needing to look into better instructions for dd-wrt upgrade to the WRT32x, to make sure such cases do not happen again. 
Thanks again @ValCher1961 - I'll be closing this issue for now, feel free to reopen it just to comment back if you'd like to. 
Thanks again for taking the time to help me. 
Time to go back to the forums for better instructions. 

Best,
