### ISSUE TITLE
boot usb / sata hdd for wrt1200ac

### ISSUE THREAD

**Issue by Lovator** [ValCher1961/McDebian_WRT3200ACM#5]
Good afternoon, I connected the USB flash drive to the usb 2.0 / esata connector, trying to determine the USB flash drive, but this message hangs, the same situation with sata hdd.

Marvell>> usb reset
(Re)start USB...
USB0:   Port (usbActive) : 0    Interface (usbType = 2) : USB EHCI 1.00
scanning bus 0 for devices... 2 USB Device(s) found
       scanning usb for storage devices...

Please tell me what could be the reason ?

**Comment by ValCher1961** [comment]
Hi, did You pre-format the disk with the command `mkfs.ext4 -O ^64bit /dev/sdX1`?

**Comment by Lovator** [comment]
Yes, hard drive too

**Comment by Lovator** [comment]
when I enter a command 'usb reset' on a flash drive the LED lights up

**Comment by ValCher1961** [comment]
One Second, I'll try to recreate your situation with the flash drive.

**Comment by Lovator** [comment]
sorry, it all worked for me, usb-hdd, sata-hdd, formatted again in ext4

**Comment by Lovator** [comment]
when loading only usb / esata works? usb 3.0 not working?

**Comment by ValCher1961** [comment]
Yes, the USB 3.0 port does not work.
Prompt, do you use USB-Flash 3.0?

**Comment by ValCher1961** [comment]
Show command output - usb info

**Comment by Chadster766** [comment]
USB3 works but not for the rootfs boot drive due to a u-boot limitation. Once the kernel is up the USB3 driver is loaded.
